# Generated by Django 5.2.6 on 2025-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name so everyone can see who has already voted. Leave blank to stay anonymous.",
                        max_length=80,
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("bbq", "Backyard BBQ Feast"),
                            ("taco", "Taco Tuesday Fiesta"),
                            ("italian", "Italian Pasta Night"),
                            ("potluck", "Comfort Food Potluck"),
                        ],
                        max_length=40,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
