# Generated by Django 4.2 on 2023-11-06 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('youtube_video_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('WS', 'Workshop'), ('SE', 'Seminar'), ('ME', 'Meetup'), ('CO', 'Conference'), ('WE', 'Webinar'), ('FE', 'Festival'), ('EX', 'Exhibition'), ('FU', 'Fundraiser'), ('CO', 'Competition')], default='ME', max_length=2)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organizer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
