# Generated by Django 4.2 on 2023-11-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0005_alter_chef_profile_pic'),
        ('meals', '0004_meal_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('chef', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together={('meal_plan', 'meal', 'day')},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='end_date',
        ),
    ]
