# Generated by Django 4.2 on 2023-12-07 06:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meal',
            managers=[
                ('postal_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
