# Generated by Django 4.2 on 2023-12-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_meal_dietary_preference'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meal',
            managers=[
            ],
        ),
    ]
