# Generated by Django 4.2 on 2023-12-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_alter_meal_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(null=True),
        ),
    ]
