# Generated by Django 5.0.1 on 2024-02-26 02:31

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_remove_ordermeal_day_ordermeal_meal_plan_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
