# Generated by Django 4.2 on 2024-02-15 12:29

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_remove_ordermeal_day_ordermeal_meal_plan_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredeint_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
