# Generated by Django 5.0.1 on 2024-03-11 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0006_chef_chef_embedding'),
        ('meals', '0012_dish_dish_embedding_ingredient_carbohydrates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='party_size',
        ),
        migrations.AddField(
            model_name='meal',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='chefs.chef'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='meals.dish'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
