# Generated by Django 4.2.10 on 2024-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_dish_dish_embedding_ingredient_ingredeint_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
