# Generated by Django 4.2.10 on 2024-02-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_ingredient_carbohydrates_ingredient_fat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredeint_embedding',
            new_name='ingredient_embedding',
        ),
    ]
