# Generated by Django 5.0.1 on 2024-03-12 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0006_chef_chef_embedding'),
        ('meals', '0013_remove_meal_party_size_meal_creator_alter_meal_chef_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(condition=models.Q(('creator__isnull', False)), fields=('name', 'creator'), name='unique_meal_per_creator'),
        ),
    ]
