# Generated by Django 5.0.1 on 2024-07-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_meal_unique_chef_meal_per_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together={('meal_plan', 'meal', 'day', 'meal_type')},
        ),
    ]
