# Generated by Django 4.2.10 on 2024-03-10 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0015_alter_meal_chef_alter_meal_dishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='party_size',
        ),
        migrations.AddField(
            model_name='meal',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meals', to=settings.AUTH_USER_MODEL),
        ),
    ]
