# Generated by Django 5.0.1 on 2024-08-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_alter_mealplanmeal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='has_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('meal_plan_meal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='meals.mealplanmeal')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='meals.mealplan')),
            ],
        ),
    ]
