# Generated by Django 4.2.10 on 2024-03-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_remove_meal_party_size_meal_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(condition=models.Q(('creator__isnull', False)), fields=('name', 'creator'), name='unique_meal_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(condition=models.Q(('chef__isnull', False)), fields=('chef', 'start_date'), name='unique_chef_meal_per_date'),
        ),
    ]
