# Generated by Django 4.2.10 on 2024-07-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_alter_meal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together={('meal_plan', 'meal', 'day', 'meal_type')},
        ),
    ]
