# Generated by Django 5.0.1 on 2024-09-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_alter_meal_dietary_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='custom_dietary_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
