# Generated by Django 5.0.1 on 2024-10-05 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0019_meal_custom_dietary_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allowed', models.JSONField(blank=True, default=list)),
                ('excluded', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='custom_dietary_preference',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dietary_preference',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together={('meal_plan', 'day', 'meal_type')},
        ),
        migrations.AddField(
            model_name='meal',
            name='custom_dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='meals', to='meals.customdietarypreference'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='meals', to='meals.dietarypreference'),
        ),
        migrations.CreateModel(
            name='MealPlanThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
