# Generated by Django 4.2.10 on 2024-08-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_shoppinglist_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='instruction',
            name='meal',
            field=models.OneToOneField(default=199, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='meals.meal'),
            preserve_default=False,
        ),
    ]
