# Generated by Django 5.0.1 on 2024-10-15 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_customdietarypreference_dietarypreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('Canned', 'Canned'), ('Dry', 'Dry Goods')], default='Canned', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
