# Generated by Django 4.2.10 on 2024-08-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0021_remove_instruction_meal_plan_instruction_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='meal',
        ),
        migrations.AddField(
            model_name='instruction',
            name='meal_plan_meal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='meals.mealplanmeal'),
        ),
    ]
