# Generated by Django 5.0.1 on 2024-10-24 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0021_pantryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='approval_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
