# Generated by Django 5.0.1 on 2024-10-24 03:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0022_mealplan_approval_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
