# Generated by Django 4.2.10 on 2024-09-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0022_remove_instruction_meal_instruction_meal_plan_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='custom_dietary_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
