# Generated by Django 5.0.1 on 2024-11-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0023_alter_mealplan_approval_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='meal_prep_preference',
            field=models.CharField(choices=[('daily', 'Daily Meal Instructions'), ('one_day_prep', 'One-Day Meal Prep')], default='daily', help_text='User preference for this week.', max_length=15),
        ),
        migrations.CreateModel(
            name='MealPlanInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField()),
                ('date', models.DateField()),
                ('is_bulk_prep', models.BooleanField(default=False)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealplan')),
            ],
        ),
    ]
