# Generated by Django 4.2.10 on 2024-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0024_mealplanthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=10),
        ),
    ]
