# Generated by Django 5.0.1 on 2025-01-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0024_mealplan_meal_prep_preference_mealplaninstruction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mealplanmeal',
            name='meal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='marked_as_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='weight_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How many ounces or grams per can/bag? (e.g. 14.5 for a 14.5 oz can.)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('oz', 'Ounces'), ('lb', 'Pounds'), ('g', 'Grams'), ('kg', 'Kilograms')], help_text="The unit for weight_per_unit, e.g. 'oz', 'lb', 'g', etc.", max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together={('user', 'item_name', 'expiration_date')},
        ),
        migrations.CreateModel(
            name='MealPlanMealPantryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('usage_unit', models.CharField(blank=True, choices=[('oz', 'Ounces'), ('lb', 'Pounds'), ('g', 'Grams'), ('kg', 'Kilograms')], help_text="Unit for quantity_used, e.g. 'oz', 'g', etc.", max_length=5, null=True)),
                ('meal_plan_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_usage', to='meals.mealplanmeal')),
                ('pantry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.pantryitem')),
            ],
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='meals.tag'),
        ),
        migrations.AddIndex(
            model_name='pantryitem',
            index=models.Index(fields=['expiration_date'], name='meals_pantr_expirat_4c1004_idx'),
        ),
    ]
