# Generated by Django 4.2.10 on 2024-09-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0025_meal_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dietary_preference',
        ),
        migrations.AddField(
            model_name='meal',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='meals', to='meals.dietarypreference'),
        ),
    ]
