# Generated by Django 4.2.10 on 2024-09-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0026_dietarypreference_remove_meal_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplanmeal',
            unique_together={('meal_plan', 'day', 'meal_type')},
        ),
    ]
