# Generated by Django 4.2.10 on 2024-10-23 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0030_mealplan_approval_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
