# Generated by Django 4.2.10 on 2024-11-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0031_alter_mealplan_approval_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='meal_prep_preference',
            field=models.CharField(choices=[('daily', 'Daily Meal Instructions'), ('one_day_prep', 'One-Day Meal Prep')], default='daily', help_text='User preference for this week.', max_length=15),
        ),
    ]
