# Generated by Django 4.2.10 on 2024-11-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0032_mealplan_meal_prep_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField()),
                ('date', models.DateField()),
                ('is_bulk_prep', models.BooleanField(default=False)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealplan')),
            ],
        ),
    ]
