# Generated by Django 4.2.10 on 2024-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0033_mealplaninstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='servings',
            field=models.PositiveIntegerField(default=1, help_text='Number of servings the meal provides.'),
        ),
    ]
