# Generated by Django 4.2.10 on 2024-12-11 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0034_meal_servings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together={('user', 'item_name', 'expiration_date')},
        ),
        migrations.AddIndex(
            model_name='pantryitem',
            index=models.Index(fields=['expiration_date'], name='meals_pantr_expirat_4c1004_idx'),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='meals.tag'),
        ),
    ]
