# Generated by Django 4.2.10 on 2024-12-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0035_tag_alter_pantryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='servings',
        ),
    ]
