# Generated by Django 4.2.10 on 2025-01-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0039_mealplanmealpantryusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='weight_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How many ounces or grams per can/bag? (e.g. 14.5 for a 14.5 oz can.)', max_digits=6, null=True),
        ),
    ]
