# Generated by Django 4.2.10 on 2025-01-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0040_pantryitem_weight_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('oz', 'Ounces'), ('lb', 'Pounds'), ('g', 'Grams'), ('kg', 'Kilograms')], help_text="The unit for weight_per_unit, e.g. 'oz', 'lb', 'g', etc.", max_length=5, null=True),
        ),
    ]
