# Generated by Django 4.2.10 on 2025-01-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0041_pantryitem_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanmealpantryusage',
            name='usage_unit',
            field=models.CharField(blank=True, choices=[('oz', 'Ounces'), ('lb', 'Pounds'), ('g', 'Grams'), ('kg', 'Kilograms')], help_text="Unit for quantity_used, e.g. 'oz', 'g', etc.", max_length=5, null=True),
        ),
    ]
