# Generated by Django 4.2.10 on 2025-01-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0042_mealplanmealpantryusage_usage_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanmeal',
            name='meal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
