# Generated by Django 4.2.10 on 2025-03-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0007_merge_0005_install_pgvector_0006_chef_chef_embedding'),
        ('meals', '0045_chefmealevent_chefmealorder_platformfeeconfig_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('chef', 'name')},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name'], name='meals_ingre_name_3e402f_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['chef', 'name'], name='meals_ingre_chef_id_1260e9_idx'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='spoonacular_id',
        ),
    ]
