# Generated by Django 4.2.10 on 2025-03-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0046_alter_ingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meal',
            name='unique_chef_meal_per_date',
        ),
        migrations.AlterField(
            model_name='chefmealevent',
            name='event_date',
            field=models.DateField(help_text='The date when the chef will prepare and serve this meal'),
        ),
        migrations.AlterField(
            model_name='chefmealevent',
            name='event_time',
            field=models.TimeField(help_text='The time when the meal will be available for pickup/delivery'),
        ),
        migrations.AlterField(
            model_name='chefmealevent',
            name='order_cutoff_time',
            field=models.DateTimeField(help_text='Deadline for placing orders (e.g., 24 hours before event)'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(condition=models.Q(('chef__isnull', False)), fields=('chef', 'start_date', 'meal_type'), name='unique_chef_meal_per_date_and_type'),
        ),
    ]
