# Generated by Django 4.2.10 on 2025-03-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0008_alter_chef_chef_embedding'),
        ('meals', '0047_remove_meal_unique_chef_meal_per_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chefmealevent',
            unique_together={('chef', 'meal', 'event_date', 'event_time', 'status')},
        ),
    ]
