# Generated by Django 4.2.10 on 2025-03-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0048_alter_chefmealevent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(max_length=100)),
                ('is_compatible', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_analyses', to='meals.meal')),
            ],
            options={
                'indexes': [models.Index(fields=['meal', 'preference_name'], name='meals_mealc_meal_id_9208ed_idx')],
                'unique_together': {('meal', 'preference_name')},
            },
        ),
    ]
