# Generated by Django 4.2.10 on 2025-03-25 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0049_mealcompatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAllergenSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe', models.BooleanField(default=False)),
                ('flagged_ingredients', models.JSONField(default=list)),
                ('reasoning', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_safety_checks', to='meals.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_allergen_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['meal', 'user'], name='meals_meala_meal_id_21c530_idx'), models.Index(fields=['is_safe'], name='meals_meala_is_safe_28702e_idx')],
                'unique_together': {('meal', 'user')},
            },
        ),
    ]
