# Generated by Django 4.2.10 on 2025-03-26 11:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0050_mealallergensafety'),
    ]

    operations = [
        # First, remove all data since we're in development and don't need it
        # Use DELETE instead of TRUNCATE for SQLite compatibility
        migrations.RunSQL(
            sql="DELETE FROM meals_mealallergensafety",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name='mealallergensafety',
            options={'verbose_name_plural': 'Meal allergen safety checks'},
        ),
        migrations.RemoveIndex(
            model_name='mealallergensafety',
            name='meals_meala_meal_id_21c530_idx',
        ),
        migrations.RemoveIndex(
            model_name='mealallergensafety',
            name='meals_meala_is_safe_28702e_idx',
        ),
        migrations.AddField(
            model_name='mealallergensafety',
            name='substitutions',
            field=models.JSONField(blank=True, null=True),
        ),
        # Simply drop and recreate the field without trying to preserve data
        migrations.RemoveField(
            model_name='mealallergensafety',
            name='flagged_ingredients',
        ),
        migrations.AddField(
            model_name='mealallergensafety',
            name='flagged_ingredients',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='mealallergensafety',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
