# Generated by Django 4.2.10 on 2025-03-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0051_alter_mealallergensafety_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='chef_meal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.chefmealevent'),
        ),
    ]
