# Generated by Django 4.2.10 on 2025-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0052_ordermeal_chef_meal_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefmealorder',
            name='price_adjustment_processed',
            field=models.BooleanField(default=False, help_text='Whether price adjustment/refund has been processed'),
        ),
    ]
