# Generated by Django 4.2.10 on 2025-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0054_order_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanmeal',
            name='already_paid',
            field=models.BooleanField(default=False, help_text='Flag indicating this meal was paid for in a previous order'),
        ),
    ]
