# Generated by Django 4.2.10 on 2025-04-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0055_mealplanmeal_already_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at the time of order creation', max_digits=6, null=True),
        ),
    ]
