# Generated by Django 4.2.10 on 2025-04-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0056_ordermeal_price_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefmealorder',
            name='meal_plan_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_order_item', to='meals.mealplanmeal'),
        ),
        migrations.AlterUniqueTogether(
            name='chefmealorder',
            unique_together={('order', 'meal_plan_meal')},
        ),
    ]
