# Generated by Django 4.2.10 on 2025-04-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0057_chefmealorder_meal_plan_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefmealorder',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
