# Generated by Django 4.2.10 on 2025-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0058_alter_chefmealorder_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='macro_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='youtube_videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
