# Generated by Django 4.2.10 on 2025-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0059_meal_macro_info_meal_youtube_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
