# Generated by Django 4.2.10 on 2025-05-10 12:24

import django.core.validators
from django.db import migrations, models
import meals.models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0060_mealplan_approval_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarypreference',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name cannot contain brackets or quotes', regex='^[^{}\\[\\]"\\\']*$'), meals.models.clean_preference_name]),
        ),
    ]
