# Generated by Django 4.2.10 on 2025-05-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0064_fix_chefmealorder_constraints'),
        ('meals', '0065_ensure_chefmealorder_fields'),
    ]

    operations = [
    ]
