# Generated by Django 4.2.10 on 2025-05-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0066_merge_20250510_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='instacart_url',
            field=models.URLField(blank=True, help_text='URL to the Instacart shopping list for this meal plan', max_length=1000, null=True),
        ),
    ]
