# Generated by Django 5.2.1 on 2025-08-08 02:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0067_mealplan_instacart_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='composed_dishes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MealDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dietary_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('target_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('is_chef_dish', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_dishes', to='meals.meal')),
            ],
            options={
                'indexes': [models.Index(fields=['meal', 'name'], name='meals_meald_meal_id_78c98f_idx')],
            },
        ),
    ]
