# Generated by Django 4.2 on 2025-10-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0071_add_chef_service_orders_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='groq_auto_approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the first auto-approval triggered by Groq batch processing.', null=True),
        ),
    ]
