# Generated by Django 5.2.6 on 2025-12-04 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0072_mealplan_groq_auto_approved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePlanPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_data', models.JSONField(help_text='JSON structure containing the sample meal plan preview')),
                ('preferences_snapshot', models.JSONField(blank=True, help_text='Snapshot of user preferences when plan was generated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample_plan_preview', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Plan Preview',
                'verbose_name_plural': 'Sample Plan Previews',
            },
        ),
    ]
