# Generated by Django 5.2.6 on 2025-12-04 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0022_rename_chefs_areaw_locatio_8f2a1c_idx_chefs_areaw_locatio_eeb8e4_idx'),
        ('meals', '0073_add_sample_plan_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Optional title for the plan (e.g., 'Holiday Week', 'Back to School')", max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Chef's notes for the customer about this plan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meal_plans', to='chefs.chef')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChefMealPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_skipped', models.BooleanField(default=False, help_text='Whether this day is skipped (holiday, vacation, etc.)')),
                ('skip_reason', models.CharField(blank=True, help_text="Reason for skipping (e.g., 'Thanksgiving', 'Family vacation')", max_length=100)),
                ('notes', models.TextField(blank=True, help_text="Chef's notes for this specific day")),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='meals.chefmealplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ChefMealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('custom_name', models.CharField(blank=True, help_text='Custom meal name if not using an existing meal', max_length=200)),
                ('custom_description', models.TextField(blank=True, help_text='Description for custom meals not in the database')),
                ('servings', models.PositiveIntegerField(default=1, help_text='Number of servings planned')),
                ('notes', models.TextField(blank=True, help_text="Chef's notes for this specific meal")),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.chefmealplanday')),
                ('meal', models.ForeignKey(blank=True, help_text="Link to an existing meal from the chef's menu", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_plan_items', to='meals.meal')),
            ],
            options={
                'ordering': ['meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('swap_meal', 'Swap this meal for something else'), ('skip_day', 'Skip this day'), ('add_day', 'Add a day to the plan'), ('dietary_note', 'Dietary concern/note'), ('general', 'General feedback')], max_length=20)),
                ('description', models.TextField(help_text="Customer's explanation of their suggestion")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Approved with Modifications')], default='pending', max_length=20)),
                ('chef_response', models.TextField(blank=True, help_text="Chef's response to the suggestion")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_suggestions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='meals.chefmealplan')),
                ('target_day', models.ForeignKey(blank=True, help_text='The specific day this suggestion is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='meals.chefmealplanday')),
                ('target_item', models.ForeignKey(blank=True, help_text='The specific meal item this suggestion is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='meals.chefmealplanitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chefmealplan',
            index=models.Index(fields=['chef', 'customer', 'status'], name='meals_chefm_chef_id_ac3466_idx'),
        ),
        migrations.AddIndex(
            model_name='chefmealplan',
            index=models.Index(fields=['customer', 'status', '-start_date'], name='meals_chefm_custome_3e97d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='chefmealplan',
            constraint=models.UniqueConstraint(fields=('chef', 'customer', 'start_date'), name='unique_chef_customer_plan_start'),
        ),
        migrations.AddIndex(
            model_name='chefmealplanday',
            index=models.Index(fields=['plan', 'date'], name='meals_chefm_plan_id_a53f13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chefmealplanday',
            unique_together={('plan', 'date')},
        ),
        migrations.AddIndex(
            model_name='chefmealplanitem',
            index=models.Index(fields=['day', 'meal_type'], name='meals_chefm_day_id_5d8628_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplansuggestion',
            index=models.Index(fields=['plan', 'status'], name='meals_mealp_plan_id_43f3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplansuggestion',
            index=models.Index(fields=['customer', '-created_at'], name='meals_mealp_custome_6e8dac_idx'),
        ),
    ]
