# Generated by Django 5.2.6 on 2025-12-04 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0023_add_sous_chef_emoji'),
        ('meals', '0074_connection_activity_and_chef_meal_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('full_week', 'Generate Full Week'), ('fill_empty', 'Fill Empty Slots'), ('single_slot', 'Single Slot')], default='fill_empty', max_length=20)),
                ('target_day', models.CharField(blank=True, max_length=20)),
                ('target_meal_type', models.CharField(blank=True, max_length=20)),
                ('custom_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('slots_requested', models.IntegerField(default=0)),
                ('slots_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_generation_jobs', to='chefs.chef')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='meals.chefmealplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan', 'status'], name='meals_mealp_plan_id_c811d7_idx'), models.Index(fields=['chef', '-created_at'], name='meals_mealp_chef_id_37afef_idx')],
            },
        ),
    ]
