# Generated by Django 5.2.6 - Index rename migration
# Made safe by checking index existence before renaming

from django.db import migrations


def rename_index_if_exists(apps, schema_editor):
    """
    Conditionally rename indexes only if they exist.
    This handles the case where indexes may have been created with different names
    in different environments.
    """
    from django.db import connection
    
    # Map of old_name -> new_name for indexes to rename
    index_renames = [
        ('meals_mealp_chef_id_d1c81c_idx', 'meals_mealp_chef_id_de9a2b_idx'),
        ('meals_mealp_chef_id_8f2b3a_idx', 'meals_mealp_chef_id_941fd7_idx'),
        ('meals_mealp_chef_id_5e7a2d_idx', 'meals_mealp_chef_id_d7288a_idx'),
        ('meals_mealp_chef_id_c8f1a9_idx', 'meals_mealp_chef_id_14e74a_idx'),
    ]
    
    with connection.cursor() as cursor:
        # Get all existing index names for this table
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'meals_mealplanreceipt'
        """)
        existing_indexes = {row[0] for row in cursor.fetchall()}
        
        for old_name, new_name in index_renames:
            if old_name in existing_indexes:
                # Rename the index
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
                print(f"Renamed index {old_name} -> {new_name}")
            elif new_name in existing_indexes:
                # Already renamed, skip
                print(f"Index {new_name} already exists, skipping")
            else:
                # Neither exists, likely created with different name, skip
                print(f"Index {old_name} not found, skipping")


def reverse_rename_index_if_exists(apps, schema_editor):
    """Reverse the index renames"""
    from django.db import connection
    
    # Map of new_name -> old_name for reversing
    index_renames = [
        ('meals_mealp_chef_id_de9a2b_idx', 'meals_mealp_chef_id_d1c81c_idx'),
        ('meals_mealp_chef_id_941fd7_idx', 'meals_mealp_chef_id_8f2b3a_idx'),
        ('meals_mealp_chef_id_d7288a_idx', 'meals_mealp_chef_id_5e7a2d_idx'),
        ('meals_mealp_chef_id_14e74a_idx', 'meals_mealp_chef_id_c8f1a9_idx'),
    ]
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'meals_mealplanreceipt'
        """)
        existing_indexes = {row[0] for row in cursor.fetchall()}
        
        for new_name, old_name in index_renames:
            if new_name in existing_indexes:
                cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')
                print(f"Reversed index rename {new_name} -> {old_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0076_add_meal_plan_receipt'),
    ]

    operations = [
        migrations.RunPython(
            rename_index_if_exists,
            reverse_rename_index_if_exists,
        ),
    ]
