# Generated by Django 5.2.6 - Index rename migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0076_add_meal_plan_receipt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mealplanreceipt',
            new_name='meals_mealp_chef_id_de9a2b_idx',
            old_name='meals_mealp_chef_id_d1c81c_idx',
        ),
        migrations.RenameIndex(
            model_name='mealplanreceipt',
            new_name='meals_mealp_chef_id_941fd7_idx',
            old_name='meals_mealp_chef_id_8f2b3a_idx',
        ),
        migrations.RenameIndex(
            model_name='mealplanreceipt',
            new_name='meals_mealp_chef_id_d7288a_idx',
            old_name='meals_mealp_chef_id_5e7a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='mealplanreceipt',
            new_name='meals_mealp_chef_id_14e74a_idx',
            old_name='meals_mealp_chef_id_c8f1a9_idx',
        ),
    ]
