# Generated by Django 5.2.8 on 2025-12-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0077_auto_rename_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefmealevent',
            name='event_date',
            field=models.DateField(help_text='The date when the chef will prepare and serve this meal share'),
        ),
        migrations.AlterField(
            model_name='chefmealevent',
            name='max_orders',
            field=models.PositiveIntegerField(help_text='Maximum number of orders the chef can fulfill for this meal share'),
        ),
        migrations.AlterField(
            model_name='chefmealevent',
            name='min_orders',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of orders needed for the meal share to proceed'),
        ),
        migrations.AlterField(
            model_name='chefmealevent',
            name='order_cutoff_time',
            field=models.DateTimeField(help_text='Deadline for placing orders for this meal share'),
        ),
    ]
