# Generated by Django 5.2.8 on 2026-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0078_alter_chefmealevent_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplangenerationjob',
            name='week_offset',
            field=models.PositiveIntegerField(default=0, help_text='0-indexed week number to generate for (0 = first week, 1 = second, etc.)'),
        ),
    ]
