# Generated by Django 5.2.8 on 2026-01-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0030_add_sous_chef_suggestion_preferences'),
        ('crm', '0004_auto_rename_indexes'),
        ('meals', '0079_add_week_offset_to_mealplangenerationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chefmealplan',
            name='unique_chef_customer_plan_start',
        ),
        migrations.AddField(
            model_name='chefmealplan',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='For off-platform clients (manual contacts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_meal_plans', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='chefmealplan',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='For platform users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_meal_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chefmealplan',
            index=models.Index(fields=['chef', 'lead', 'status'], name='meals_chefm_chef_id_bc1641_idx'),
        ),
        migrations.AddIndex(
            model_name='chefmealplan',
            index=models.Index(fields=['lead', 'status', '-start_date'], name='meals_chefm_lead_id_0ec9b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='chefmealplan',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('chef', 'customer', 'start_date'), name='unique_chef_customer_plan_start'),
        ),
        migrations.AddConstraint(
            model_name='chefmealplan',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False)), fields=('chef', 'lead', 'start_date'), name='unique_chef_lead_plan_start'),
        ),
    ]
