# Generated by Django 4.2 on 2023-07-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='chefs/')),
                ('chef_request', models.BooleanField(default=False)),
                ('chef_request_experience', models.TextField(blank=True, null=True)),
                ('chef_request_bio', models.TextField(blank=True, null=True)),
                ('chef_request_profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
