# Generated by Django 4.2 on 2023-11-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_chefs', '0001_initial'),
        ('chefs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='primary_postal_code',
        ),
        migrations.AddField(
            model_name='chef',
            name='serving_postalcodes',
            field=models.ManyToManyField(related_name='serving_chefs', through='local_chefs.ChefPostalCode', to='local_chefs.postalcode'),
        ),
        migrations.AddField(
            model_name='chefrequest',
            name='requested_postalcodes',
            field=models.ManyToManyField(blank=True, to='local_chefs.postalcode'),
        ),
    ]
