# Generated by Django 4.2 on 2023-11-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_remove_chef_primary_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='chefs/profile_pics'),
        ),
    ]
