# Generated by Django 4.2.10 on 2024-02-23 06:38

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0005_install_pgvector'),

    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='chef_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
