# Generated by Django 4.2.10 on 2024-12-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0005_install_pgvector'),
        ('chefs', '0006_chef_chef_embedding'),
    ]

    operations = [
    ]
