# Generated by Django 4.2.10 on 2025-03-18 04:24

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0007_merge_0005_install_pgvector_0006_chef_chef_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
