# Generated by Django 4.2.10 on 2025-06-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0008_alter_chef_chef_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_request_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_request_experience',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
