# Generated by Django 4.2.10 on 2025-06-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0009_alter_chef_chef_request_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='experience',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
