# Generated by Django 4.2.10 on 2025-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0010_alter_chef_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_request_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_request_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
