# Generated by Django 5.2.1 on 2025-08-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0011_alter_chef_chef_request_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chefs/photos/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chefs.chef')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
