# Generated by Django 5.2.1 on 2025-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0012_chefphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefDefaultBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chefs/banners/defaults/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='chef',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='chefs/banners/'),
        ),
    ]
