# Generated by Django 5.2.1 on 2025-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0014_waitlist_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chefwaitlistsubscription',
            new_name='chefs_chefw_chef_id_8dc66e_idx',
            old_name='chefs_chefw_chef_id_a8d8e1_idx',
        ),
        migrations.RenameIndex(
            model_name='chefwaitlistsubscription',
            new_name='chefs_chefw_user_id_5694c3_idx',
            old_name='chefs_chefw_user_id_a7b4a9_idx',
        ),
        migrations.AlterField(
            model_name='chefavailabilitystate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chefwaitlistconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chefwaitlistsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
