# Generated by Django 5.2.6 on 2025-10-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0017_enhance_chefphoto_gallery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chefphoto',
            new_name='chefs_chefp_chef_id_c39b96_idx',
            old_name='chefs_photo_chef_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chefphoto',
            new_name='chefs_chefp_chef_id_5e57c3_idx',
            old_name='chefs_photo_chef_category_idx',
        ),
        migrations.RenameIndex(
            model_name='chefphoto',
            new_name='chefs_chefp_chef_id_7e9213_idx',
            old_name='chefs_photo_chef_public_idx',
        ),
    ]
