# Generated by Django 5.2.6 on 2025-10-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0018_rename_chefs_photo_chef_created_idx_chefs_chefp_chef_id_c39b96_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='background_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chef',
            name='food_handlers_cert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chef',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chef',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin approval for platform listing'),
        ),
        migrations.CreateModel(
            name='ChefVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('insurance', 'Insurance'), ('background', 'Background Check'), ('food_handlers', 'Food Handler Certificate'), ('other', 'Other')], max_length=32)),
                ('file', models.FileField(upload_to='chefs/verification_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejected_reason', models.TextField(blank=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_docs', to='chefs.chef')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
