# Generated by Django 5.2.6 on 2025-12-04 05:49

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0019_chef_background_checked_chef_food_handlers_cert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(help_text='Normalized postal code', max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('notified', models.BooleanField(default=False, help_text='Whether user has been notified of chef availability')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area Waitlist Entry',
                'verbose_name_plural': 'Area Waitlist Entries',
                'indexes': [models.Index(fields=['postal_code', 'country', 'notified'], name='chefs_areaw_postal__b34b93_idx'), models.Index(fields=['user', 'notified'], name='chefs_areaw_user_id_2c7fa3_idx')],
                'unique_together': {('user', 'postal_code', 'country')},
            },
        ),
    ]
