# Generated by Django 5.2.6 on 2025-12-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0021_refactor_area_waitlist_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='areawaitlist',
            new_name='chefs_areaw_locatio_eeb8e4_idx',
            old_name='chefs_areaw_locatio_8f2a1c_idx',
        ),
    ]
