# Generated by Django 5.2.6 on 2025-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0022_rename_chefs_areaw_locatio_8f2a1c_idx_chefs_areaw_locatio_eeb8e4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='sous_chef_emoji',
            field=models.CharField(blank=True, default='🧑\u200d🍳', help_text='Emoji icon for the Sous Chef assistant widget', max_length=10),
        ),
    ]
