# Generated by Django 5.2.6 on 2025-12-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0024_resource_planning_models'),
        ('meals', '0075_add_meal_plan_generation_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefprepplancommitment',
            options={'ordering': ['service_date', 'meal_name']},
        ),
        migrations.RemoveConstraint(
            model_name='chefprepplancommitment',
            name='commitment_type_matches_reference',
        ),
        migrations.AddField(
            model_name='chefprepplancommitment',
            name='chef_meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_plan_links', to='meals.chefmealplan'),
        ),
        migrations.AddField(
            model_name='chefprepplancommitment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chefprepplancommitment',
            name='commitment_type',
            field=models.CharField(choices=[('client_meal_plan', 'Client Meal Plan'), ('meal_event', 'Meal Event'), ('service_order', 'Service Order')], max_length=20),
        ),
    ]
