# Generated by Django 5.2.6 on 2025-12-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0026_chefpaymentlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chefpaymentlink',
            new_name='chefs_chefp_chef_id_94742e_idx',
            old_name='chefs_chefp_chef_id_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='chefpaymentlink',
            new_name='chefs_chefp_chef_id_9c09d2_idx',
            old_name='chefs_chefp_chef_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chefpaymentlink',
            new_name='chefs_chefp_lead_id_fb9529_idx',
            old_name='chefs_chefp_lead_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='chefpaymentlink',
            new_name='chefs_chefp_custome_7b785b_idx',
            old_name='chefs_chefp_cust_status_idx',
        ),
        migrations.RenameIndex(
            model_name='chefpaymentlink',
            new_name='chefs_chefp_stripe__664455_idx',
            old_name='chefs_chefp_stripe_link_idx',
        ),
        migrations.RenameIndex(
            model_name='chefpaymentlink',
            new_name='chefs_chefp_stripe__2450f6_idx',
            old_name='chefs_chefp_stripe_sess_idx',
        ),
    ]
