# Generated by Django 5.2.6 on 2025-12-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0027_auto_rename_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='Calendly booking URL for client consultations', max_length=500, null=True),
        ),
    ]






