# Generated by Django 5.2.8 on 2025-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0028_add_calendly_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='default_currency',
            field=models.CharField(default='usd', help_text='Default currency for payment links and stats (ISO 4217 code)', max_length=3),
        ),
    ]
