# Generated by Django 5.2.8 on 2026-01-22 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0030_add_sous_chef_suggestion_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCalendlyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendly_url', models.URLField(help_text="Admin's Calendly URL for chef verification meetings", max_length=500)),
                ('meeting_title', models.CharField(default='Chef Verification Call', help_text='Title shown to chefs when scheduling', max_length=200)),
                ('meeting_description', models.TextField(blank=True, help_text='Description of what to expect in the verification call')),
                ('is_required', models.BooleanField(default=True, help_text='Whether the meeting is required before chef can be fully activated')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable the Calendly meeting step globally')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Calendly Config',
                'verbose_name_plural': 'Platform Calendly Config',
            },
        ),
        migrations.CreateModel(
            name='ChefVerificationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='not_scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When the meeting is/was scheduled for', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the meeting was completed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes from the verification meeting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_meeting', to='chefs.chef')),
                ('marked_complete_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_chef_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef Verification Meeting',
                'verbose_name_plural': 'Chef Verification Meetings',
            },
        ),
    ]
