# Generated by Django 5.2.8 on 2026-01-22 15:45

from django.db import migrations, models


def set_existing_chefs_live(apps, schema_editor):
    """
    Set is_live=True for existing verified chefs who have active Stripe accounts.
    This preserves current visibility for chefs who were already operational.
    """
    Chef = apps.get_model('chefs', 'Chef')
    StripeConnectAccount = apps.get_model('meals', 'StripeConnectAccount')

    # Get chef IDs with active Stripe accounts
    active_stripe_chef_ids = StripeConnectAccount.objects.filter(
        is_active=True
    ).values_list('chef_id', flat=True)

    # Set is_live=True for verified chefs with active Stripe
    updated = Chef.objects.filter(
        is_verified=True,
        id__in=active_stripe_chef_ids
    ).update(is_live=True)

    if updated:
        print(f"Set is_live=True for {updated} existing verified chef(s) with active Stripe")


def reverse_set_live(apps, schema_editor):
    """Reverse: set all is_live back to False"""
    Chef = apps.get_model('chefs', 'Chef')
    Chef.objects.update(is_live=False)


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0031_platformcalendlyconfig_chefverificationmeeting'),
        ('meals', '0001_initial'),  # Ensure meals migrations are applied for StripeConnectAccount
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Chef has completed setup and chosen to be visible in the public directory'),
        ),
        migrations.RunPython(set_existing_chefs_live, reverse_set_live),
    ]
