# Generated by Django 5.2.8 on 2026-02-01 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0033_sous_chef_memory_system'),
        ('crm', '0004_auto_rename_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientcontext',
            name='unique_chef_client_context',
        ),
        migrations.RemoveConstraint(
            model_name='clientcontext',
            name='unique_chef_lead_context',
        ),
        migrations.RemoveConstraint(
            model_name='souschefusage',
            name='unique_chef_date_usage',
        ),
        migrations.RenameIndex(
            model_name='clientcontext',
            new_name='chefs_clien_chef_id_aa6b71_idx',
            old_name='chefs_client_chef_client_idx',
        ),
        migrations.RenameIndex(
            model_name='clientcontext',
            new_name='chefs_clien_chef_id_3c04e0_idx',
            old_name='chefs_client_chef_lead_idx',
        ),
        migrations.RenameIndex(
            model_name='souschefusage',
            new_name='chefs_sousc_chef_id_0c43f7_idx',
            old_name='chefs_usage_chef_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='clientcontext',
            unique_together={('chef', 'client'), ('chef', 'lead')},
        ),
        migrations.AlterUniqueTogether(
            name='souschefusage',
            unique_together={('chef', 'date')},
        ),
    ]
