# Generated by Django 5.2.9 on 2026-02-01 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0034_remove_clientcontext_unique_chef_client_context_and_more'),
        ('crm', '0004_auto_rename_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcomed', models.BooleanField(default=False, help_text='Has seen welcome modal')),
                ('welcomed_at', models.DateTimeField(blank=True, help_text='When chef saw welcome modal', null=True)),
                ('setup_started', models.BooleanField(default=False, help_text='Has started the setup wizard')),
                ('setup_started_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed', models.BooleanField(default=False, help_text='Has completed the setup wizard')),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('setup_skipped', models.BooleanField(default=False, help_text='Skipped the setup wizard')),
                ('setup_skipped_at', models.DateTimeField(blank=True, null=True)),
                ('personality_set', models.BooleanField(default=False, help_text='Has set communication style')),
                ('personality_choice', models.CharField(blank=True, help_text='Selected personality: professional, friendly, efficient', max_length=50)),
                ('first_dish_added', models.BooleanField(default=False, help_text='Has added their first dish')),
                ('first_dish_added_at', models.DateTimeField(blank=True, null=True)),
                ('first_client_added', models.BooleanField(default=False, help_text='Has added their first client (platform or lead)')),
                ('first_client_added_at', models.DateTimeField(blank=True, null=True)),
                ('first_conversation', models.BooleanField(default=False, help_text='Has had their first Sous Chef conversation')),
                ('first_conversation_at', models.DateTimeField(blank=True, null=True)),
                ('first_memory_saved', models.BooleanField(default=False, help_text='Has saved their first memory')),
                ('first_memory_saved_at', models.DateTimeField(blank=True, null=True)),
                ('first_order_completed', models.BooleanField(default=False, help_text='Has completed their first order')),
                ('first_order_completed_at', models.DateTimeField(blank=True, null=True)),
                ('proactive_enabled', models.BooleanField(default=False, help_text='Has enabled proactive features')),
                ('proactive_enabled_at', models.DateTimeField(blank=True, null=True)),
                ('tips_shown', models.JSONField(blank=True, default=list, help_text='List of tip IDs that have been shown')),
                ('tips_dismissed', models.JSONField(blank=True, default=list, help_text='List of tip IDs that have been permanently dismissed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='chefs.chef')),
            ],
            options={
                'verbose_name': 'Chef Onboarding State',
                'verbose_name_plural': 'Chef Onboarding States',
            },
        ),
        migrations.CreateModel(
            name='ChefProactiveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch to enable/disable all proactive features')),
                ('notify_birthdays', models.BooleanField(default=True, help_text='Notify about upcoming client birthdays')),
                ('notify_anniversaries', models.BooleanField(default=True, help_text='Notify about anniversaries and special dates')),
                ('notify_followups', models.BooleanField(default=True, help_text='Remind to follow up with inactive clients')),
                ('notify_todos', models.BooleanField(default=True, help_text='Remind about to-do items')),
                ('notify_seasonal', models.BooleanField(default=True, help_text='Suggest seasonal ingredients and menus')),
                ('notify_milestones', models.BooleanField(default=True, help_text='Celebrate client milestones (e.g., 10th order)')),
                ('birthday_lead_days', models.PositiveSmallIntegerField(default=7, help_text='Days before birthday to notify')),
                ('anniversary_lead_days', models.PositiveSmallIntegerField(default=7, help_text='Days before anniversary to notify')),
                ('followup_threshold_days', models.PositiveSmallIntegerField(default=30, help_text='Days of inactivity before suggesting follow-up')),
                ('notification_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest')], default='daily', help_text='How often to receive notifications', max_length=20)),
                ('channel_in_app', models.BooleanField(default=True, help_text='Show notifications in the app')),
                ('channel_email', models.BooleanField(default=False, help_text='Send notification emails')),
                ('channel_push', models.BooleanField(default=False, help_text='Send push notifications (future)')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (e.g., 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours (e.g., 08:00)', null=True)),
                ('quiet_hours_timezone', models.CharField(default='UTC', help_text='Timezone for quiet hours', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_settings', to='chefs.chef')),
            ],
            options={
                'verbose_name': 'Chef Proactive Settings',
                'verbose_name_plural': 'Chef Proactive Settings',
            },
        ),
        migrations.CreateModel(
            name='ChefNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('birthday', 'Birthday reminder'), ('anniversary', 'Anniversary reminder'), ('followup', 'Follow-up suggestion'), ('todo', 'To-do reminder'), ('seasonal', 'Seasonal suggestion'), ('milestone', 'Client milestone'), ('tip', 'Contextual tip'), ('system', 'System notification')], default='system', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_context', models.JSONField(blank=True, default=dict, help_text='Context for actions: prePrompt, navigation target, etc.')),
                ('sent_in_app', models.BooleanField(default=False)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to send (for digest mode)', null=True)),
                ('dedup_key', models.CharField(blank=True, db_index=True, help_text='Key for deduplication', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chefs.chef')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_notifications', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Chef Notification',
                'verbose_name_plural': 'Chef Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chef', 'status', '-created_at'], name='chefs_chefn_chef_id_1f642b_idx'), models.Index(fields=['chef', 'notification_type'], name='chefs_chefn_chef_id_6489e6_idx'), models.Index(fields=['dedup_key'], name='chefs_chefn_dedup_k_9ff80c_idx')],
            },
        ),
    ]
