# Generated by Django 5.2.10 on 2026-02-02 13:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0036_chefworkspace_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefTelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_orders', models.BooleanField(default=True, help_text='Notify when a new order comes in')),
                ('notify_order_updates', models.BooleanField(default=True, help_text='Notify on order status changes')),
                ('notify_schedule_reminders', models.BooleanField(default=True, help_text='Send schedule reminders')),
                ('notify_customer_messages', models.BooleanField(default=False, help_text='Notify on direct customer messages')),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0), help_text='Start of quiet hours (no notifications)')),
                ('quiet_hours_end', models.TimeField(default=datetime.time(8, 0), help_text='End of quiet hours')),
                ('quiet_hours_enabled', models.BooleanField(default=True, help_text='Enable quiet hours')),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_settings', to='chefs.chef')),
            ],
            options={
                'verbose_name': 'Chef Telegram Settings',
                'verbose_name_plural': 'Chef Telegram Settings',
            },
        ),
        migrations.CreateModel(
            name='ChefTelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text="Telegram's unique user ID", unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username (without @)', max_length=255, null=True)),
                ('telegram_first_name', models.CharField(blank=True, help_text="User's first name on Telegram", max_length=255, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='When the account was linked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the link is currently active')),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to='chefs.chef')),
            ],
            options={
                'verbose_name': 'Chef Telegram Link',
                'verbose_name_plural': 'Chef Telegram Links',
                'indexes': [models.Index(fields=['telegram_user_id'], name='chefs_cheft_telegra_421a75_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='The one-time token value', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was created')),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('used', models.BooleanField(default=False, help_text='Whether the token has been used')),
                ('chef', models.ForeignKey(help_text='Chef who generated this token', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to='chefs.chef')),
            ],
            options={
                'verbose_name': 'Telegram Link Token',
                'verbose_name_plural': 'Telegram Link Tokens',
                'indexes': [models.Index(fields=['token'], name='chefs_teleg_token_847c23_idx'), models.Index(fields=['expires_at'], name='chefs_teleg_expires_64dcdb_idx')],
            },
        ),
    ]
