# Generated by Django 5.2.10 on 2026-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0037_telegram_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='food_handlers_cert_expiry',
            field=models.DateField(blank=True, help_text='Food handler certificate expiration date', null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='food_handlers_cert_number',
            field=models.CharField(blank=True, help_text='Food handler certificate number', max_length=100),
        ),
        migrations.AddField(
            model_name='chef',
            name='food_handlers_cert_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the food handler certificate was verified', null=True),
        ),
    ]
