# Generated by Django 5.2.10 on 2026-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0038_add_food_handlers_cert_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefproactivesettings',
            name='notify_cert_expiry',
            field=models.BooleanField(default=True, help_text='Notify about expiring certifications (food handler, insurance)'),
        ),
        migrations.AlterField(
            model_name='chefnotification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('birthday', 'Birthday reminder'), ('anniversary', 'Anniversary reminder'), ('followup', 'Follow-up suggestion'), ('todo', 'To-do reminder'), ('seasonal', 'Seasonal suggestion'), ('milestone', 'Client milestone'), ('tip', 'Contextual tip'), ('system', 'System notification'), ('cert_expiry', 'Certification expiry')], default='system', max_length=20),
        ),
    ]
