# Generated by Django 4.2 on 2023-11-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
