# Generated by Django 4.2 on 2023-11-20 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0002_delete_mealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='query',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='response',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='content',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatlog',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatlog',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='customer_dashboard.chatthread'),
            preserve_default=False,
        ),
    ]
