# Generated by Django 4.2 on 2023-11-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0003_remove_chatlog_query_remove_chatlog_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='openai_thread_id',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
