# Generated by Django 4.2 on 2023-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0004_chatthread_openai_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
