# Generated by Django 4.2 on 2023-11-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0005_chatthread_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='title',
        ),
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
