# Generated by Django 4.2 on 2023-11-23 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0007_chatthread_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(blank=True, choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Gluten-Free', 'Gluten-Free'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Low-Calorie', 'Low-Calorie'), ('Low-Sodium', 'Low-Sodium'), ('High-Protein', 'High-Protein'), ('Dairy-Free', 'Dairy-Free'), ('Nut-Free', 'Nut-Free'), ('Raw Food', 'Raw Food'), ('Whole 30', 'Whole 30'), ('Low-FODMAP', 'Low-FODMAP'), ('Diabetic-Friendly', 'Diabetic-Friendly')], default='None', max_length=20, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
