# Generated by Django 4.2 on 2023-11-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0009_chatlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
