# Generated by Django 4.2 on 2023-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0010_delete_chatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltracking',
            name='goal_description',
            field=models.TextField(max_length=1000),
        ),
    ]
