# Generated by Django 4.2 on 2024-01-14 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_remove_ordermeal_day_ordermeal_meal_plan_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0012_userhealthmetrics_delete_foodpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_size', models.CharField(max_length=100)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_intake', to='meals.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_intake', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
