# Generated by Django 4.2.10 on 2024-03-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0018_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_dashboard.chatthread'),
        ),
    ]
