# Generated by Django 5.0.1 on 2024-09-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0019_toolcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersummary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersummary',
            name='summary',
            field=models.TextField(default='No summary available'),
        ),
    ]
