# Generated by Django 4.2.10 on 2024-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0020_toolcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersummary',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
