# Generated by Django 4.2.10 on 2024-08-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0021_usersummary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersummary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
