# Generated by Django 4.2.10 on 2024-08-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0022_alter_usersummary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersummary',
            name='summary',
            field=models.TextField(default='No summary available'),
        ),
    ]
