# Generated by Django 4.2.10 on 2025-04-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0024_assistantemailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='openai_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
