# Generated by Django 4.2.10 on 2025-04-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0025_alter_chatthread_openai_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='turn_context_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
