# Generated by Django 4.2.10 on 2025-04-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0026_chatthread_turn_context_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='turn_context_history',
        ),
        migrations.AddField(
            model_name='chatthread',
            name='openai_input_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
