# Generated by Django 4.2.10 on 2025-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0027_remove_chatthread_turn_context_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='latest_response_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='openai_thread_id',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
