# Generated by Django 4.2.10 on 2025-04-24 05:07
from django.db import migrations

def forwards(apps, schema_editor):
    ChatThread = apps.get_model('customer_dashboard', 'ChatThread')
    updated = 0
    for ct in ChatThread.objects.all():
        # Make sure openai_thread_id is *always* a list
        if isinstance(ct.openai_thread_id, str) and ct.openai_thread_id:
            ct.openai_thread_id = [ct.openai_thread_id]

        # If it's a list but empty, nothing we can do
        if not ct.openai_thread_id:
            ct.save(update_fields=['openai_thread_id'])
            continue

        # latest_response_id = last element in the list if missing
        if not getattr(ct, "latest_response_id", None):
            ct.latest_response_id = ct.openai_thread_id[-1]
            ct.save(update_fields=['openai_thread_id', 'latest_response_id'])
            updated += 1
    print(f"Back-filled {updated} chat threads")

class Migration(migrations.Migration):
    dependencies = [('customer_dashboard', '0028_chatthread_latest_response_id_and_more')]
    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]