# Generated by Django 4.2.10 on 2025-04-28 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0030_chatthread_announcement_shown_weeklyannouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyannouncement',
            options={'ordering': ['-week_start', 'country'], 'verbose_name': 'Weekly Announcement', 'verbose_name_plural': 'Weekly Announcements'},
        ),
        migrations.AlterField(
            model_name='weeklyannouncement',
            name='content',
            field=models.TextField(help_text='The announcement text that will be shown to users via MJ, the meal planning assistant.'),
        ),
        migrations.AlterField(
            model_name='weeklyannouncement',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Leave blank for a global announcement that shows to all users. Select a country to target users from that region.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyannouncement',
            name='created_by',
            field=models.ForeignKey(help_text='The admin who created this announcement.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyannouncement',
            name='week_start',
            field=models.DateField(help_text='The Monday that starts this announcement week. If you select another day, it will be adjusted to the previous Monday.'),
        ),
    ]
