# Generated by Django 4.2.10 on 2025-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0032_userdailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailysummary',
            name='recommend_prompt',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdailysummary',
            name='ticket',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
