# Generated by Django 4.2.10 on 2025-05-07 04:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0033_userdailysummary_recommend_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyannouncement',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Leave blank for a global announcement that shows to all users regardless of region. Global announcements will be shown together with region-specific announcements.', max_length=2, null=True),
        ),
    ]
