# Generated by Django 4.2.10 on 2025-05-08 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0034_alter_weeklyannouncement_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=10)),
                ('last_summary_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Chat Summary',
                'verbose_name_plural': 'User Chat Summaries',
            },
        ),
        migrations.CreateModel(
            name='ChatSessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(default=django.utils.timezone.localdate)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=10)),
                ('last_message_processed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='customer_dashboard.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session Summary',
                'verbose_name_plural': 'Chat Session Summaries',
                'ordering': ['-summary_date'],
                'unique_together': {('user', 'thread', 'summary_date')},
            },
        ),
    ]
