# Generated by Django 4.2.10 on 2025-05-17 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0035_userchatsummary_chatsessionsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantemailtoken',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assistantemailtoken',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='assistantemailtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='assistantemailtoken',
            name='auth_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='assistantemailtoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantemailtoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assistantemailtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_auth_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserEmailSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
