# Generated by Django 4.2.10 on 2025-05-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0036_remove_assistantemailtoken_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantemailtoken',
            name='auth_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assistantemailtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useremailsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
