# Generated by Django 4.2.10 on 2025-05-17 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0037_alter_assistantemailtoken_auth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantemailtoken',
            name='auth_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
