# Generated by Django 5.2.6 on 2025-12-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0037_souschefthread_souschefmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='souschefthread',
            new_name='customer_da_chef_id_20e95a_idx',
            old_name='customer_da_chef_id_9e8a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='souschefthread',
            new_name='customer_da_chef_id_ea3b61_idx',
            old_name='customer_da_chef_id_2b5f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='souschefthread',
            new_name='customer_da_chef_id_a4644e_idx',
            old_name='customer_da_chef_id_a2c1b9_idx',
        ),
    ]
