# Generated by Django 4.2.10 on 2025-05-19 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0038_alter_assistantemailtoken_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAggregationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_identifier', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('user_email_token', models.CharField(max_length=255)),
                ('original_subject', models.CharField(max_length=1024)),
                ('in_reply_to_header', models.TextField(blank=True, null=True)),
                ('email_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_thread_context_id_initial', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_aggregation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedMessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_dashboard.emailaggregationsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
