# Generated by Django 5.2.6 on 2025-12-04 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0019_chef_background_checked_chef_food_handlers_cert_and_more'),
        ('crm', '0002_add_household_and_dietary_tracking'),
        ('customer_dashboard', '0038_rename_customer_da_chef_id_9e8a1c_idx_customer_da_chef_id_20e95a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='souschefthread',
            name='conversation_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary of truncated conversation history'),
        ),
        migrations.AddField(
            model_name='souschefthread',
            name='messages_summarized_count',
            field=models.IntegerField(default=0, help_text='Number of messages that have been summarized'),
        ),
        migrations.AddField(
            model_name='souschefthread',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the conversation summary was last generated', null=True),
        ),
        migrations.CreateModel(
            name='FamilyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('preference', 'Preference'), ('tip', 'Useful Tip'), ('avoid', 'Things to Avoid'), ('success', 'What Worked Well')], max_length=20)),
                ('content', models.TextField(help_text='The insight content (max 500 chars)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive insights won't be shown in context")),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_insights', to='chefs.chef')),
                ('customer', models.ForeignKey(blank=True, help_text='Platform customer this insight is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef_insights', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='CRM lead this insight is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef_insights', to='crm.lead')),
                ('source_thread', models.ForeignKey(blank=True, help_text='The conversation thread where this insight was discovered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='customer_dashboard.souschefthread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chef', 'customer'], name='customer_da_chef_id_34382c_idx'), models.Index(fields=['chef', 'lead'], name='customer_da_chef_id_52422e_idx'), models.Index(fields=['chef', 'is_active'], name='customer_da_chef_id_b147d1_idx')],
            },
        ),
    ]
