# Generated by Django 4.2.10 on 2025-05-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0039_emailaggregationsession_aggregatedmessagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaggregationsession',
            name='email_thread_id',
            field=models.CharField(blank=True, help_text="e.g., Gmail's thread ID", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailaggregationsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Set to False after Celery task processes it.'),
        ),
        migrations.AlterField(
            model_name='emailaggregationsession',
            name='openai_thread_context_id_initial',
            field=models.CharField(blank=True, help_text='OpenAI thread ID if passed with the first email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailaggregationsession',
            name='recipient_email',
            field=models.EmailField(help_text="The original sender's email to reply to.", max_length=254),
        ),
        migrations.AlterField(
            model_name='emailaggregationsession',
            name='user_email_token',
            field=models.CharField(help_text="The user's token from mj+<token>@sautai.com", max_length=255),
        ),
        migrations.AlterField(
            model_name='useremailsession',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useremailsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PreAuthenticationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('original_subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('in_reply_to_header', models.TextField(blank=True, null=True)),
                ('email_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_thread_context_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_message_for_token', to='customer_dashboard.assistantemailtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_auth_pending_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
