# Generated by Django 5.2.6 on 2025-12-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0039_souschef_summary_and_insights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goaltracking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userhealthmetrics',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalorieIntake',
        ),
        migrations.DeleteModel(
            name='GoalTracking',
        ),
        migrations.DeleteModel(
            name='UserHealthMetrics',
        ),
    ]
