# Generated by Django 4.2.10 on 2025-05-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0040_alter_emailaggregationsession_email_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaggregationsession',
            name='original_subject',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
