# Generated by Django 5.2.8 on 2026-02-01 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0034_remove_clientcontext_unique_chef_client_context_and_more'),
        ('crm', '0004_auto_rename_indexes'),
        ('customer_dashboard', '0040_remove_health_tracking_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('pattern', 'Pattern'), ('preference', 'Preference'), ('lesson', 'Lesson Learned'), ('todo', 'To-Do/Reminder')], help_text='Category of this memory', max_length=20)),
                ('content', models.TextField(help_text='The memory content (max 1000 chars)', max_length=1000)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Metadata: family_id, source (conversation, observation), tags, etc.')),
                ('importance', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Normal'), (4, 'High'), (5, 'Critical')], default=3, help_text='How important is this memory? Higher = more likely to be recalled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='When this memory was last used in a conversation', null=True)),
                ('access_count', models.IntegerField(default=0, help_text='How many times this memory has been recalled')),
                ('is_active', models.BooleanField(default=True, help_text="Soft delete - inactive memories won't be recalled")),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='chefs.chef')),
                ('customer', models.ForeignKey(blank=True, help_text='If this memory is about a specific platform customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_memories', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='If this memory is about a specific CRM lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_memories', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Chef Memory',
                'verbose_name_plural': 'Chef Memories',
                'ordering': ['-importance', '-updated_at'],
                'indexes': [models.Index(fields=['chef', 'memory_type', 'is_active'], name='customer_da_chef_id_9391ce_idx'), models.Index(fields=['chef', 'importance', 'is_active'], name='customer_da_chef_id_6cffa2_idx'), models.Index(fields=['chef', 'customer'], name='customer_da_chef_id_830d49_idx'), models.Index(fields=['chef', 'lead'], name='customer_da_chef_id_51a296_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChefProactiveInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('followup_needed', 'Follow-up Needed'), ('batch_opportunity', 'Batch Cooking Opportunity'), ('seasonal_suggestion', 'Seasonal Suggestion'), ('client_win', 'Client Win'), ('scheduling_tip', 'Scheduling Tip')], max_length=30)),
                ('title', models.CharField(help_text='Short headline for the insight', max_length=200)),
                ('content', models.TextField(help_text='Detailed recommendation and context')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('actioned_at', models.DateTimeField(blank=True, help_text='When the chef took action on this insight', null=True)),
                ('action_taken', models.CharField(blank=True, help_text='What action was taken (if any)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this insight is no longer relevant', null=True)),
                ('action_data', models.JSONField(blank=True, default=dict, help_text='Data needed to take action (e.g., family_id, suggested message)')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_insights', to='chefs.chef')),
                ('customer', models.ForeignKey(blank=True, help_text='Platform customer this insight is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef_proactive_insights', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='CRM lead this insight is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef_proactive_insights', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Chef Proactive Insight',
                'verbose_name_plural': 'Chef Proactive Insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chef', 'is_read', 'is_dismissed'], name='customer_da_chef_id_fab8f4_idx'), models.Index(fields=['chef', 'insight_type', 'is_dismissed'], name='customer_da_chef_id_5a41f5_idx'), models.Index(fields=['chef', 'priority', 'is_dismissed'], name='customer_da_chef_id_b2af86_idx'), models.Index(fields=['chef', 'expires_at'], name='customer_da_chef_id_963081_idx')],
            },
        ),
    ]
