# Generated by Django 5.2.9 on 2026-02-01 11:09

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0041_chefmemory_chefproactiveinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefmemory',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, help_text='Embedding vector for semantic/hybrid search', null=True),
        ),
    ]
