# Generated by Django 5.2.6 - Index rename migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chefmembership',
            new_name='memberships_status_0270b4_idx',
            old_name='memberships_status_c63b5c_idx',
        ),
        migrations.RenameIndex(
            model_name='chefmembership',
            new_name='memberships_stripe__6c66c1_idx',
            old_name='memberships_stripe__7db9a0_idx',
        ),
        migrations.RenameIndex(
            model_name='chefmembership',
            new_name='memberships_stripe__c2ced6_idx',
            old_name='memberships_stripe__1b7b3e_idx',
        ),
        migrations.RenameIndex(
            model_name='membershippaymentlog',
            new_name='memberships_members_335f94_idx',
            old_name='memberships_members_a2d4e3_idx',
        ),
        migrations.RenameIndex(
            model_name='membershippaymentlog',
            new_name='memberships_stripe__eeadd9_idx',
            old_name='memberships_stripe__4e5c8f_idx',
        ),
    ]
