# Generated by Django 4.2 on 2023-11-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_week_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodPreferences',
        ),
    ]
