# Generated by Django 4.2 on 2023-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_new_email_customuser_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initial_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
