# Generated by Django 4.2 on 2023-07-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shipping_address',
        ),
    ]
