# Generated by Django 4.2 on 2024-01-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_remove_customuser_preferences_alter_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChefAddress',
        ),
    ]
