# Generated by Django 4.2 on 2024-01-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_delete_chefaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Peanuts', 'Peanuts'), ('Tree nuts', 'Tree nuts'), ('Milk', 'Milk'), ('Egg', 'Egg'), ('Wheat', 'Wheat'), ('Soy', 'Soy'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish'), ('Sesame', 'Sesame'), ('Mustard', 'Mustard'), ('Celery', 'Celery'), ('Lupin', 'Lupin'), ('Sulfites', 'Sulfites'), ('Molluscs', 'Molluscs'), ('Corn', 'Corn'), ('Gluten', 'Gluten'), ('Kiwi', 'Kiwi'), ('Latex', 'Latex'), ('Pine Nuts', 'Pine Nuts'), ('Sunflower Seeds', 'Sunflower Seeds'), ('Poppy Seeds', 'Poppy Seeds'), ('Fennel', 'Fennel'), ('Peach', 'Peach'), ('Banana', 'Banana'), ('Avocado', 'Avocado'), ('Chocolate', 'Chocolate'), ('Coffee', 'Coffee'), ('Cinnamon', 'Cinnamon'), ('Garlic', 'Garlic'), ('Chickpeas', 'Chickpeas'), ('Lentils', 'Lentils')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='custom_auth.allergy'),
        ),
    ]
