# Generated by Django 4.2 on 2024-01-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_allergy_customuser_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allergies',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Gluten-Free', 'Gluten-Free'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Low-Calorie', 'Low-Calorie'), ('Low-Sodium', 'Low-Sodium'), ('High-Protein', 'High-Protein'), ('Dairy-Free', 'Dairy-Free'), ('Nut-Free', 'Nut-Free'), ('Raw Food', 'Raw Food'), ('Whole 30', 'Whole 30'), ('Low-FODMAP', 'Low-FODMAP'), ('Diabetic-Friendly', 'Diabetic-Friendly'), ('Everything', 'Everything')], default='None', max_length=70),
        ),
    ]
