# Generated by Django 4.2 on 2024-01-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_remove_customuser_allergies_delete_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='input_postalcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
