# Generated by Django 4.2 on 2024-01-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_address_input_postalcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postalcode',
        ),
    ]
