# Generated by Django 5.0.1 on 2024-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_customuser_custom_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_daily_instructions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_instruction_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_meal_plan_saved',
            field=models.BooleanField(default=True),
        ),
    ]
