# Generated by Django 4.2.10 on 2024-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_customuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
