# Generated by Django 5.0.1 on 2024-10-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0019_alter_address_city_alter_address_country_and_more'),
        ('meals', '0020_customdietarypreference_dietarypreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_dietary_preference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dietary_preference',
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='users', to='meals.customdietarypreference'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='users', to='meals.dietarypreference'),
        ),
    ]
