# Generated by Django 5.0.1 on 2024-10-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0020_remove_customuser_custom_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emergency_supply_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
