# Generated by Django 4.2.10 on 2024-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0020_alter_customuser_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_daily_instructions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_instruction_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_meal_plan_saved',
            field=models.BooleanField(default=True),
        ),
    ]
