# Generated by Django 5.0.1 on 2025-01-12 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_customuser_emergency_supply_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_allergies_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_servings',
            field=models.PositiveIntegerField(default=1, help_text='Number of servings the user wants meals scaled to.'),
        ),
    ]
