# Generated by Django 5.0.1 on 2025-01-12 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0022_customuser_custom_allergies_array_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_allergies_array',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
