# Generated by Django 4.2.10 on 2024-09-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0026_dietarypreference_remove_meal_dietary_preference_and_more'),
        ('custom_auth', '0022_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dietary_preference',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='users', to='meals.dietarypreference'),
        ),
    ]
