# Generated by Django 4.2.10 on 2024-10-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0028_customdietarypreference_and_more'),
        ('custom_auth', '0023_remove_customuser_dietary_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_dietary_preference',
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='users', to='meals.customdietarypreference'),
        ),
    ]
