# Generated by Django 4.2.10 on 2024-10-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0024_remove_customuser_custom_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emergency_supply_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
