# Generated by Django 4.2.10 on 2024-11-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0025_customuser_emergency_supply_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='family_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of people the user cooks for.'),
        ),
    ]
