# Generated by Django 4.2.10 on 2024-12-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0026_customuser_family_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='family_size',
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_servings',
            field=models.PositiveIntegerField(default=1, help_text='Number of servings the user wants meals scaled to.'),
        ),
    ]
