# Generated by Django 4.2.10 on 2024-12-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0028_customuser_custom_allergies_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_allergies',
        ),
    ]
