# Generated by Django 4.2.10 on 2024-12-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0029_remove_customuser_custom_allergies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='custom_allergies_array',
            new_name='custom_allergies',
        ),
    ]
