# Generated by Django 4.2.10 on 2025-05-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0032_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('jp', 'Japanese'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
