# Generated by Django 4.2.10 on 2025-05-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0032_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_daily_instructions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_instruction_generation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_meal_plan_saved',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unsubscribed_from_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
