# Generated by Django 4.2.10 on 2025-05-24 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0033_remove_customuser_email_daily_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
