# Generated by Django 4.2.10 on 2025-05-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0034_alter_customuser_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
