# Generated by Django 4.2.10 on 2025-05-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0035_alter_customuser_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_daily_instructions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_instruction_generation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_meal_plan_saved',
        ),
        migrations.AddField(
            model_name='customuser',
            name='unsubscribed_from_emails',
            field=models.BooleanField(default=False),
        ),
    ]
