# Generated by Django 5.2.1 on 2025-06-27 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0035_alter_customuser_email_token'),
        ('meals', '0067_mealplan_instacart_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_servings',
        ),
        migrations.AddField(
            model_name='customuser',
            name='household_member_count',
            field=models.PositiveIntegerField(default=1, help_text="Total number of people in the user's household."),
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dietary_preferences', models.ManyToManyField(blank=True, related_name='household_members', to='meals.dietarypreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
