# Generated by Django 5.2.6 on 2025-12-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0039_customuser_auto_meal_plans_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sample_plan_generated',
            field=models.BooleanField(default=False, help_text='Whether the user has generated their one-time sample meal plan preview.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sample_plan_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the sample plan was generated.', null=True),
        ),
    ]
