# Generated by Django 5.2.8 on 2026-01-22 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0041_rename_postal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='custom_allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
