# Generated by Django 4.2.10 on 2024-12-20 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0002_rename_date_posted_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='not_both_meal_and_mealplan',
        ),
        migrations.RemoveField(
            model_name='review',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='review',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
