# Generated by Django 4.2.10 on 2024-12-20 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0004_review_meal_review_meal_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='review',
            name='meal_plan',
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 20, 2, 8, 53, 326803, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
