# Generated by Django 4.2.10 on 2024-12-27 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0005_remove_review_meal_remove_review_meal_plan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
