# Generated by Django 5.2.6 on 2025-12-03 13:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Peanuts', 'Peanuts'), ('Tree nuts', 'Tree nuts'), ('Milk', 'Milk'), ('Egg', 'Egg'), ('Wheat', 'Wheat'), ('Soy', 'Soy'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish'), ('Sesame', 'Sesame'), ('Gluten', 'Gluten'), ('None', 'None')], max_length=50), blank=True, default=list, help_text='Food allergies for this contact', size=None),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Custom allergies not in the standard list', size=None),
        ),
        migrations.AddField(
            model_name='lead',
            name='dietary_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Gluten-Free', 'Gluten-Free'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Low-Calorie', 'Low-Calorie'), ('Low-Sodium', 'Low-Sodium'), ('High-Protein', 'High-Protein'), ('Dairy-Free', 'Dairy-Free'), ('Nut-Free', 'Nut-Free'), ('Diabetic-Friendly', 'Diabetic-Friendly'), ('Everything', 'Everything')], max_length=50), blank=True, default=list, help_text='Dietary preferences for this contact', size=None),
        ),
        migrations.AddField(
            model_name='lead',
            name='household_size',
            field=models.PositiveIntegerField(default=1, help_text='Total number of people in this household'),
        ),
        migrations.CreateModel(
            name='LeadHouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to primary contact (spouse, child, parent, etc.)', max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('dietary_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Gluten-Free', 'Gluten-Free'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Low-Calorie', 'Low-Calorie'), ('Low-Sodium', 'Low-Sodium'), ('High-Protein', 'High-Protein'), ('Dairy-Free', 'Dairy-Free'), ('Nut-Free', 'Nut-Free'), ('Diabetic-Friendly', 'Diabetic-Friendly'), ('Everything', 'Everything')], max_length=50), blank=True, default=list, size=None)),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Peanuts', 'Peanuts'), ('Tree nuts', 'Tree nuts'), ('Milk', 'Milk'), ('Egg', 'Egg'), ('Wheat', 'Wheat'), ('Soy', 'Soy'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish'), ('Sesame', 'Sesame'), ('Gluten', 'Gluten'), ('None', 'None')], max_length=50), blank=True, default=list, size=None)),
                ('custom_allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='crm.lead')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
