# Generated by Django 5.2.6 on 2025-12-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_email_verification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_lead_email_v_ac4d17_idx',
            old_name='crm_lead_email_v_a4e8b5_idx',
        ),
    ]
