# Generated by Django 5.2.11 on 2026-02-05 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_rename_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='anniversary',
            field=models.DateField(blank=True, help_text='Anniversary date (for annual reminders)', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='birthday_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Birth day (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='birthday_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Birth month (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
