# Generated by Django 4.2 on 2023-07-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_initial'),
        ('menus', '0002_menu_description_menu_party_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('chef', 'start_date', 'end_date', 'party_size')},
        ),
    ]
