# Generated by Django 4.2 on 2023-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_dish_price_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Menu Name', max_length=200),
        ),
    ]
