# Generated by Django 4.2 on 2023-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='meal_types',
            field=models.ManyToManyField(to='menus.mealtype'),
        ),
    ]
