# Generated by Django 4.2 on 2023-11-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChefPostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_postalcodes', to='chefs.chef')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_chefs', to='local_chefs.postalcode')),
            ],
            options={
                'unique_together': {('chef', 'postal_code')},
            },
        ),
    ]
