# Generated by Django 4.2 on 2023-11-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_remove_chef_primary_postal_code_and_more'),
        ('local_chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefpostalcode',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chefs.chef'),
        ),
        migrations.AlterField(
            model_name='chefpostalcode',
            name='postal_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_chefs.postalcode'),
        ),
    ]
