# Generated by Django 4.2.10 on 2025-03-15 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_chefs', '0003_postalcode_country_alter_postalcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='display_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chefpostalcode',
            name='postal_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefpostalcode_set', to='local_chefs.postalcode'),
        ),
    ]
