# Generated by Django 5.2.6 on 2025-12-06 14:40

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_chefs', '0005_postalcode_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='place_name',
            field=models.CharField(blank=True, help_text='Place name from GeoNames', max_length=255),
        ),
        migrations.CreateModel(
            name='AdministrativeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name in English (e.g., 'Shibuya')", max_length=255)),
                ('name_local', models.CharField(blank=True, help_text="Local language name (e.g., '渋谷区')", max_length=255)),
                ('area_type', models.CharField(choices=[('country', 'Country'), ('state', 'State/Province'), ('prefecture', 'Prefecture'), ('county', 'County'), ('city', 'City'), ('ward', 'Ward'), ('district', 'District'), ('neighborhood', 'Neighborhood'), ('other', 'Other')], default='city', max_length=20)),
                ('country', django_countries.fields.CountryField(help_text='Country this area belongs to', max_length=2)),
                ('geonames_id', models.BigIntegerField(blank=True, help_text='GeoNames ID for sync', null=True, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, help_text='Cached boundary polygon as GeoJSON', null=True)),
                ('postal_code_count', models.PositiveIntegerField(default=0, help_text='Cached count of postal codes in this area')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent area (e.g., Shibuya -> Tokyo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='local_chefs.administrativearea')),
            ],
            options={
                'verbose_name_plural': 'Administrative areas',
            },
        ),
        migrations.AddField(
            model_name='postalcode',
            name='admin_area',
            field=models.ForeignKey(blank=True, help_text='The city/ward/district this postal code belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postal_codes', to='local_chefs.administrativearea'),
        ),
        migrations.AddIndex(
            model_name='administrativearea',
            index=models.Index(fields=['country', 'area_type'], name='local_chefs_country_779d26_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativearea',
            index=models.Index(fields=['name'], name='local_chefs_name_97d63f_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativearea',
            index=models.Index(fields=['parent'], name='local_chefs_parent__87e383_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='administrativearea',
            unique_together={('name', 'parent', 'country', 'area_type')},
        ),
    ]
