# Generated by Django 5.2.6 on 2025-12-06 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0027_auto_rename_indexes'),
        ('local_chefs', '0006_add_administrative_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved')], default='pending', max_length=20)),
                ('chef_notes', models.TextField(blank=True, help_text="Chef's explanation for why they want to serve these areas")),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the review decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_area_requests', to='chefs.chef')),
                ('requested_areas', models.ManyToManyField(blank=True, help_text='Administrative areas requested', related_name='area_requests', to='local_chefs.administrativearea')),
                ('requested_postal_codes', models.ManyToManyField(blank=True, help_text='Individual postal codes requested', related_name='postal_requests', to='local_chefs.postalcode')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_area_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chef', 'status'], name='local_chefs_chef_id_322fce_idx'), models.Index(fields=['status', 'created_at'], name='local_chefs_status_af8619_idx')],
            },
        ),
    ]
