# Generated by Django 5.2.6 on 2025-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_chefs', '0007_add_service_area_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearearequest',
            name='approved_areas',
            field=models.ManyToManyField(blank=True, help_text='Areas that were approved (subset of requested_areas for partial approval)', related_name='approved_requests', to='local_chefs.administrativearea'),
        ),
        migrations.AddField(
            model_name='servicearearequest',
            name='approved_postal_codes',
            field=models.ManyToManyField(blank=True, help_text='Postal codes that were approved (subset of requested for partial approval)', related_name='approved_postal_requests', to='local_chefs.postalcode'),
        ),
    ]
