# Generated by Django 5.2.1 on 2025-09-10 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_services', '0001_initial'),
        ('chefs', '0016_chef_is_on_break'),
        ('custom_auth', '0039_customuser_auto_meal_plans_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefserviceoffering',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='chefserviceorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chefservicepricetier',
            options={'ordering': ['household_min', 'household_max', 'id']},
        ),
        migrations.AddIndex(
            model_name='chefserviceoffering',
            index=models.Index(fields=['chef', 'service_type', 'active'], name='chef_servic_chef_id_2b19d7_idx'),
        ),
        migrations.AddIndex(
            model_name='chefserviceorder',
            index=models.Index(fields=['chef', 'status'], name='chef_servic_chef_id_1a37fd_idx'),
        ),
        migrations.AddIndex(
            model_name='chefserviceorder',
            index=models.Index(fields=['customer', 'status'], name='chef_servic_custome_e488ec_idx'),
        ),
        migrations.AddIndex(
            model_name='chefservicepricetier',
            index=models.Index(fields=['offering', 'active'], name='chef_servic_offerin_7757c0_idx'),
        ),
    ]
