# Generated by Django 5.2.6 on 2025-09-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_services', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefservicepricetier',
            name='desired_unit_amount_cents',
            field=models.PositiveIntegerField(),
        ),
    ]
