# Generated by Django 4.2 on 2025-10-30 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefs', '0019_chef_background_checked_chef_food_handlers_cert_and_more'),
        ('chef_services', '0005_alter_chefserviceoffering_max_travel_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefserviceoffering',
            name='target_customers',
            field=models.ManyToManyField(blank=True, related_name='personalized_service_offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChefCustomerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('ended', 'Ended')], default='pending', max_length=20)),
                ('initiated_by', models.CharField(choices=[('chef', 'Chef'), ('customer', 'Customer')], max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_connections', to='chefs.chef')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='chefcustomerconnection',
            index=models.Index(fields=['chef', 'customer'], name='chef_servic_chef_id_74baa5_idx'),
        ),
        migrations.AddIndex(
            model_name='chefcustomerconnection',
            index=models.Index(fields=['chef', 'status'], name='chef_servic_chef_id_afdcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='chefcustomerconnection',
            index=models.Index(fields=['customer', 'status'], name='chef_servic_custome_e64823_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chefcustomerconnection',
            unique_together={('chef', 'customer')},
        ),
    ]
