# Generated by Django 5.2.6 on 2025-12-04 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_services', '0006_chefserviceoffering_target_customers_and_more'),
        ('chefs', '0022_rename_chefs_areaw_locatio_8f2a1c_idx_chefs_areaw_locatio_eeb8e4_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chefcustomerconnection',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Last time there was a message exchange', null=True),
        ),
        migrations.AddField(
            model_name='chefcustomerconnection',
            name='last_order_at',
            field=models.DateTimeField(blank=True, help_text='Last time customer placed an order with this chef', null=True),
        ),
        migrations.AddField(
            model_name='chefcustomerconnection',
            name='last_plan_update_at',
            field=models.DateTimeField(blank=True, help_text='Last time a meal plan was created or updated', null=True),
        ),
        migrations.AddIndex(
            model_name='chefcustomerconnection',
            index=models.Index(fields=['customer', 'status', '-last_order_at'], name='chef_servic_custome_bf064c_idx'),
        ),
    ]
