# Generated by Django 5.2.8 on 2025-12-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_services', '0007_connection_activity_and_chef_meal_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefservicepricetier',
            name='currency',
            field=models.CharField(default='usd', help_text='ISO 4217 currency code (lowercase)', max_length=10),
        ),
        migrations.AlterField(
            model_name='chefservicepricetier',
            name='desired_unit_amount_cents',
            field=models.PositiveIntegerField(help_text='Amount in smallest currency unit (cents for USD, whole units for JPY)'),
        ),
    ]
