# Generated by Django 5.2.1 on 2025-08-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('achievement', 'Achievement Earned'), ('chef_connect', 'Chef Connect'), ('review', 'Review'), ('level_up', 'Level Up'), ('meal_planned', 'Meal Planned'), ('cooking', 'Cooking'), ('streak_update', 'Streak Updated'), ('goal_completed', 'Weekly Goal Completed')], max_length=50),
        ),
    ]
